default_platform(:ios)

platform :ios do
  desc "Test Build"
  lane :test_build do
    xcodebuild(
      project: "MTRPL-CI.xcodeproj",
      scheme: "MTRPL-CI",
      configuration: "Debug",
      sdk: 'iphonesimulator',
      destination: 'generic/platform=iOS',
      clean: true,
      build: true,
      )
  end
end
