default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Test Build"
  lane :test_build do
    xcodebuild(
      project: "MTRPL-CI.xcodeproj",
      scheme: "MTRPL-CI",
      configuration: "Debug",
      sdk: 'iphonesimulator',
      destination: 'generic/platform=iOS',
      clean: true,
      build: true,
      )
  end
end
